### ISSUE TITLE
Nástroj na tvorbu MLAB layoutu nefunguje v kicad7

### ISSUE THREAD

**Issue by roman-dvorak** [MLAB-project/kicad-mlab#3]
```
Prepare MLAB module with pattern 3x3
Traceback (most recent call last):
  File "/home/roman/.local/share/kicad/7.0/scripting/plugins/mlab_layout.py", line 69, in OnClick
    ed.SetStart(pcbnew.wxPointMM(offset[0]+0.254, offset[1]+0.254))
  File "/usr/lib/python3/dist-packages/pcbnew.py", line 14609, in SetStart
    return _pcbnew.EDA_SHAPE_SetStart(self, aStart)
TypeError: in method 'EDA_SHAPE_SetStart', argument 2 of type 'VECTOR2I const &'
```

**Comment by roman-dvorak** [comment]
Tohle je už vyřešené, Aktuálně mi to funguje.
